export const Fields = {
	BatteryLevel: {
		type: 'number',
		label: 'Battery Alert Level',
		id: 'barlevel',
		min: 1,
		max: 5,
		default: 2,
		required: true,
		range: true,
	},
	Frequency: {
		type: 'textinput',
		label: 'Frequency (MHz)',
		id: 'value',
		default: '470.000',
		regex: '/^(4[7-9][0-9]|[5-8][0-9]{2}|9[0-2][0-9]|93[0-7])\\.\\d(00|25|50|75)$/',
	},
	GainIncrement: {
		type: 'number',
		label: 'Gain Value (dB)',
		id: 'gain',
		min: 1,
		max: 60,
		default: 3,
		required: true,
		range: true,
	},
	GainSet: {
		type: 'number',
		label: 'Gain Value (dB)',
		id: 'gain',
		min: -18,
		max: 42,
		default: 0,
		required: true,
		range: true,
	},
	Mute: {
		type: 'dropdown',
		label: 'Mute/Unmute/Toggle',
		id: 'choice',
		default: 'ON',
		choices: Choices.OnOffToggle,
	},
	Name: {
		type: 'textinput',
		label: 'Name (8 characters max)',
		id: 'name',
		default: '',
		regex: '/^.{1,8}$/',
	},
	RfOutput: {
		type: 'dropdown',
		label: 'On/Off',
		id: 'onoff',
		default: 'RF_ON',
		choices: Choices.RfOutput,
	},
	RfPower: {
		type: 'dropdown',
		label: 'Power Level',
		id: 'power',
		default: '10',
		choices: Choices.RfPower,
	},
	SlotStatus: {
		type: 'dropdown',
		label: 'Status',
		id: 'value',
		default: 'LINKED.ACTIVE',
		choices: Choices.SlotStatus,
	},
}

export const Choices = {
	OnOffToggle: [
		{ id: 'ON', label: 'Mute' },
		{ id: 'OFF', label: 'Unmute' },
		{ id: 'TOGGLE', label: 'Toggle Mute/Unmute' },
	],
	RfOutput: [
		{ id: 'RF_ON', label: 'RF On' },
		{ id: 'RF_MUTE', label: 'RF Mute' },
	],
	RfPower: [
		{ id: 'LOW', label: 'Low' },
		{ id: 'NORMAL', label: 'Normal' },
		{ id: 'HIGH', label: 'High' },
	],
	SlotStatus: [
		{ id: 'EMPTY', label: 'Empty' },
		{ id: 'STANDARD', label: 'Standard' },
		{ id: 'LINKED.INACTIVE', label: 'Linked - Inactive' },
		{ id: 'LINKED.ACTIVE', label: 'Linked - Active' },
	],
}
